### ISSUE TITLE
Data Extraction and Combination Issues

### ISSUE THREAD

**Issue by kevintorrico** [mohammap22/WisconsinWolfAnalysis#63]
General:

- Wolf Population: the wolf population values are extracted from the chart, but the corresponding years are missing. This issue essentially applies to any question we're answering about wolves.

Specific Files:
- proportion_of_wolves: tick data not extracted from the PDF
- wolf_and_deer_pop: deer population cannot be extracted from PDF.
- wolf_pop_cwd_positives: cwd positives cannot be extracted from PDF.
- wolf_pop_deer_harvest: statewide deer harvest cannot be extracted from PDF.
- wolf_pop_dogs_killed: rows with killed dogs are unlabeled out of PDF_parser making identification challenging without hard coding.
- wolf_pop_hunter_observations: deer seen per hunted hour cannot be extracted from PDF.
- wolf_pop_investigations: incidents for all years are not extracted from PDF.

**Comment by mohammap22** [comment]
Thanks for taking a look at the outputs Kevin. Do you believe it worth it to edit the pdf_parser code further for some of these specific cases, or should we end up biting the bullet? It is difficult to find settings and logic that applies to **all** of our use cases (each different table), so we would need to make multiple pdf_parser files. Personally, I'd rather not have to resort to that.
